version: '3.3'

services:
  lms:
    container_name: lms
    image: varrcan/docker-image-lms:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./squeezebox:/srv/squeezebox
      - ${AUDIO_DIR}:/srv/music:ro
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
      - "1900:1900/udp"
    restart: always

volumes:
  squeezebox:
